#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals
from datetime import datetime

# Site info
AUTHOR = 'Name Name'
ROBOTS = 'index, follow'

SITENAME = 'Simplify-Next Theme'
SITETITLE = 'Simplify-Next Theme'
SITESUBTITLE = 'A simple theme for blog, powered by Bootstrap and Pelican'
SITEDESCRIPTION = 'A simple theme for blog, powered by Bootstrap and Pelican'
SITELOGO = 'logo.png'
COPYRIGHT_YEAR = datetime.now().year

# when developing: don't specify URL, use document-relative URLs 
SITEURL = ''
RELATIVE_URLS = True

# Locale and Language
LOCALE = 'en_US'
DEFAULT_LANG = 'en'
TIMEZONE = 'Asia/Saigon'
DATE_FORMATS = {
    'en': '%b %d, %Y',
}

# Build settings
PATH = 'content'
THEME = '../' # parent folder

ARTICLE_PATHS = ['blog']
ARTICLE_URL = 'blog/{slug}.html'
ARTICLE_SAVE_AS = 'blog/{slug}.html'
ARTICLE_PRIMARY_PATH = 'blog'

PAGE_PATHS = [
    'pages'
]

DIRECT_TEMPLATES = [
    'index', 
    'authors', 
    'categories', 
    'tags', 
    'archives', 
    '404',
    'search',
]

# below pages are not included in the theme, but you want to customize them in html and layout
# TEMPLATE_PAGES = {
#     'pages/test.html': 'pages/test.html'
# }

DEFAULT_PAGINATION = 10
DEFAULT_DATE = (2010, 10, 10, 10, 10, 10)

OUTPUT_PATH = 'output'
DELETE_OUTPUT_DIRECTORY = True

# THEME = '../' points at the repo root, which recursively contains this
# example/ dir (and therefore OUTPUT_PATH). Without ignoring it, `pelican
# --autoreload` watches its own output and rebuilds forever. DELETE_OUTPUT_DIRECTORY
# makes each build delete+recreate 'output' itself, so both the bare directory
# path and everything under it need to be excluded.
IGNORE_FILES = ['**/.*', '**/output', '**/output/**']

# Feed generation, usually not needed when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Advanced Settings
FORMATTED_FIELDS = [] # removed 'summary'
STATIC_PATHS = [
	'images',
	'favicon.ico',
    'logo.png',
    'logo.svg',
	'.htaccess',
	'robots.txt',
    'search-index.st', # generated by the search-index task; copied by Pelican itself
                        
]



PLUGINS = [
    'sitemap', # generate sitemap document, see <https://www.sitemaps.org>
    'minchin.pelican.plugins.post_stats', # generate post statistics
    'related_posts', # find articles those share common tags
    'neighbors', # find next, previous article
    'share_post', # static sharing buttons
]

SITEMAP = {
    'format': 'xml',
    'priorities': {
        'articles': 0.5,
        'indexes': 0.5,
        'pages': 0.5
    },
    'changefreqs': {
        'articles': 'monthly',
        'indexes': 'daily',
        'pages': 'monthly'
    }
}

RELATED_POSTS_MAX = 5
RELATED_POSTS_SKIP_SAME_CATEGORY = False

# Markdown extensions
TYPOGRIFY = True
MARKDOWN = {
    'extensions': [
        # official extensions
        'markdown.extensions.extra', # include extensions: abbr, attr_list, def_list, fenced_code, footnotes, tables
        'markdown.extensions.codehilite', # to generate code color scheme using pygments
        'markdown.extensions.meta', # to parse key:value pairs at the begining of file
        'markdown.extensions.sane_lists',# for better list 
        'markdown.extensions.toc', # add Table of Content
        'markdown.extensions.nl2br', # easily to add new line, but make attr_list and legacy_attrs hard to control        
        #'markdown.extensions.legacy_attrs', # insert attribs into element, but markdown already has a built-in function that do the same thing
        #'markdown.extensions.legacy_em', # to use legacy emphasis
        #'markdown.extensions.smarty', # converts ASCII dashes, quotes and ellipses to their HTML entity equivalents
        #'markdown.extensions.wikilinks',

        # 3rd party extensions
        'markdown_checklist.extension', # show checkbox in list
        #'markdown_captions', # convert <img> to <figure> and <figcaption>
    ],
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
    },
    'output_format': 'html5',
}

# Social widget
SOCIAL = {
    'github': 'https://github.com/CHANGE-ME',
    'linkedin': 'https://www.linkedin.com/in/CHANGE-ME',
    'twitter': 'https://x.com/CHANGE-ME',
}

# Site validation
# CLAIM_GOOGLE = 'CHANGE-ME'
# CLAIM_BING = 'CHANGE-ME'

# Search Engine
# static search index (search-index.st) is generated by Stork via Docker,
# see the `search-index` task in taskfiles/Taskfile_pelican.yml and docker/stork/Dockerfile
# or use a dynamic engine like Google Custom Search Engine
# GOOGLE_CSE_ID = 'CHANGE-ME'

# Comments
# DISQUS_SITENAME = "CHANGE-ME-github-io"

# Sharing
# SHARE_POST = True # static sharing buttons for articles (Twitter, LinkedIn)

# Tracking
# GOOGLE_ANALYTICS = "UA-CHANGE-ME" # old method
# GOOGLE_SITE_TAG = "UA-CHANGE-ME" # new method to use with Tag Manager
# GOOGLE_TAG_MANAGER = ""

# Ads
# GOOGLE_ADSENSE = {
#     'id': 'ca-pub-9105473411342324',
#     'ads': {
#         'home': '7539833074',
#         'sidebar': '5458247602',
#         'page': '',
#         'article': '',
#     }
# }

# HEAP_ANALYTICS = ""

# MATOMO_SITENAME = 'CHANGE-MEgithubio' # new site of PIWIK

# GDPR / Cookie Consent
# GDPR_CONSENT = True # show an accept/reject banner and block GA/GTM/Matomo/Heap/AdSense/Disqus until the visitor accepts
# GDPR_PRIVACY_POLICY_URL = '/pages/privacy-policy.html' # linked from the consent banner and footer; see example/content/pages/privacy-policy.md